[DET-217]Implement time performance test
soleil-ica/Lima-camera-imxpad pull request #2
Opened 2022-02-15 15:02 UTC by Tenockles

- Implement time test with Lima core framework.
 - Start implementation for ImXpad server direct access

2022-02-16 10:13 UTC, soleil-ica requested changes

2022-02-16 10:13 UTC, soleil-ica commented on src/imXpadCamera.cpp
> +
Pourquoi as tu du faire ces ajouts?

2022-02-16 12:53 UTC, Tenockles commented on src/imXpadCamera.cpp
> +
Ces modifications ne devraient pas être dans la pull request, une erreur de ma part sans doute

2022-03-01 08:55 UTC, soleil-ica commented on src/imXpadCamera.cpp
> +
peux tu les enlever

2022-03-09 14:51 UTC, merged